name: feel_the_art
description: Card game based on artworks.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  persistent_bottom_nav_bar_v2: any
  introduction_screen: ^3.0.1
  carousel_slider: ^4.1.1
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: ElsieSwashCaps
      fonts:
        - asset: assets/fonts/ElsieSwashCaps-Regular.ttf
        - asset: assets/fonts/ElsieSwashCaps-Black.ttf
          weight: 700
