name: feel_the_art
description: Card game based on artworks.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  persistent_bottom_nav_bar_v2: any
  introduction_screen: ^3.0.1
  carousel_slider: ^4.1.1
  device_preview: ^1.1.0
  avatar_glow: ^2.0.2
  animated_text_kit: ^4.2.2
  auto_animated: any
  animations: ^2.0.7
  shared_preferences: ^2.0.15
  flutter_animation_progress_bar: ^2.3.1
  multiavatar: ^0.1.5
  fl_chart: ^0.55.2
  http: ^0.13.5
  provider: ^6.0.4
  percent_indicator: ^4.2.2
  google_fonts: ^2.3.1
  device_info_plus: ^8.0.0
  flutter_secure_storage: ^7.0.1
  flutter_screenutil: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: any

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/background/
    - assets/cards/images/
    - assets/cards/cards.json

  fonts:
    - family: Hind
      fonts:
        - asset: assets/fonts/Hind-Regular.ttf
        - asset: assets/fonts/Hind-Light.ttf
          weight: 300
        - asset: assets/fonts/Hind-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Hind-Bold.ttf
          weight: 700
    - family: ElsieSwashCaps
      fonts:
        - asset: assets/fonts/ElsieSwashCaps-Regular.ttf
        - asset: assets/fonts/ElsieSwashCaps-Black.ttf
          weight: 700
